// Generated by CoffeeScript 1.10.0
(function() {
  var Alchemy, Entity, alchemyEntities;

  Entity = require('./Entity');

  Alchemy = require('./alchemy.js');

  alchemyEntities = function(text, apiKey) {
    var alchemy, entityMap, mapEntityName;
    alchemy = new Alchemy(apiKey);
    entityMap = {
      Person: 'personName',
      Company: 'companyName'
    };
    mapEntityName = (function(_this) {
      return function(name) {
        if (entityMap[name] != null) {
          return entityMap[name];
        } else {
          return name.toLowerCase();
        }
      };
    })(this);
    return new Promise(function(resolve) {
      return alchemy.entities("text", text, {
        'language': 'german'
      }, function(res) {
        var entity, i, len, ref, results;
        results = [];
        ref = res.entities;
        for (i = 0, len = ref.length; i < len; i++) {
          entity = ref[i];
          results.push(new Entity(mapEntityName(entity.type), entity.text));
        }
        return resolve(results);
      });
    });
  };

  module.exports = alchemyEntities;

}).call(this);
