// Generated by CoffeeScript 1.10.0
(function() {
  var Entity;

  module.exports = Entity = (function() {
    function Entity(type, value, meta) {
      this.type = type;
      this.value = value;
      this.meta = meta;
    }

    return Entity;

  })();

}).call(this);
