// Generated by CoffeeScript 1.10.0
(function() {
  var determineAmbiguities, getTargets;

  getTargets = function(domainTypes, labels, listName) {
    var domainType, entityTargets, field, i, j, k, label, len, len1, len2, listType, ref, target;
    entityTargets = [];
    for (i = 0, len = labels.length; i < len; i++) {
      label = labels[i];
      for (j = 0, len1 = domainTypes.length; j < len1; j++) {
        domainType = domainTypes[j];
        if (domainType.name === label) {
          ref = domainType.fields;
          for (k = 0, len2 = ref.length; k < len2; k++) {
            field = ref[k];
            listType = listName.substring(0, listName.length - 4);
            if (field.name === listType) {
              target = {
                label: label,
                field: field.name
              };
              entityTargets.push(target);
            }
          }
        }
      }
    }
    return entityTargets;
  };

  determineAmbiguities = function(domainTypes, labels, entities) {
    var entityList, entityListsWithTargets, listName;
    entityListsWithTargets = {};
    for (listName in entities) {
      entityList = entities[listName];
      if (entityList.length > 0) {
        entityList.targets = getTargets(domainTypes, labels, listName);
        if (entityList.targets.length > 0) {
          entityListsWithTargets[listName] = entityList;
        }
      }
    }
    return entityListsWithTargets;
  };

  module.exports = determineAmbiguities;

}).call(this);
