// Generated by CoffeeScript 1.10.0
(function() {
  var _, ambiguities, associateEntities, disambiguate;

  ambiguities = require('./ambiguities');

  disambiguate = require('./disambiguator');

  _ = require('underscore');

  associateEntities = function(domainTypes, labels, entities) {
    var entityList, listName, listType;
    entities = ambiguities(domainTypes, labels, entities);
    for (listName in entities) {
      entityList = entities[listName];
      if (entityList.targets.length === 1 && entityList.length === 1) {
        entityList[0].target = entityList.targets[0];
      } else {
        listType = listName.substring(0, listName.length - 4);
        if (disambiguate[listType] != null) {
          entityList = disambiguate[listType](entityList, entities);
        } else {
          throw new Error(listName + ' entity affiliation could not be determined.');
        }
      }
      entities[listName] = entityList;
    }
    return entities;
  };

  module.exports = associateEntities;

}).call(this);
