// Generated by CoffeeScript 1.10.0
(function() {
  var Mapper, rules;

  rules = require('./rules');

  Mapper = require('./mapper');

  module.exports = function(net, domainTypes) {
    var features, i, labels, len, mapper, rule, trainingOptions, trainingVectors;
    mapper = new Mapper(domainTypes);
    features = mapper.features;
    labels = mapper.classes;
    trainingVectors = [];
    for (i = 0, len = rules.length; i < len; i++) {
      rule = rules[i];
      trainingVectors = trainingVectors.concat(rule(labels, features));
    }
    trainingOptions = {
      errorThresh: 0.00001,
      iterations: 200000,
      learingRate: 0.5
    };
    net.train(trainingVectors, trainingOptions);
    return net;
  };

}).call(this);
