// Generated by CoffeeScript 1.10.0
(function() {
  var Classifier, Flextractor, Promise, fillForms, ner;

  Promise = require('bluebird');

  fillForms = require('./ie/index');

  Classifier = require('./classifier/index');

  ner = require('./ner/index');

  Flextractor = (function() {
    function Flextractor(domainTypes, opts) {
      this.domainTypes = domainTypes;
      this.classifier = new Classifier(this.domainTypes);
      this.ner = ner;
      this.apiKeys = opts.apiKeys;
    }

    Flextractor.prototype.extract = function(text) {
      return this.ner(text, this.apiKeys).then((function(_this) {
        return function(entities) {
          var entityName, listName, recognizedFeatures;
          recognizedFeatures = [];
          for (listName in entities) {
            entityName = listName.substring(0, listName.length - 4);
            recognizedFeatures.push(entityName);
          }
          return _this.classifier.classify(recognizedFeatures).then(function(labels) {
            var datasets;
            datasets = fillForms(_this.domainTypes, labels, entities);
            return datasets;
          });
        };
      })(this));
    };

    return Flextractor;

  })();

  module.exports = Flextractor;

}).call(this);
