// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, alchemyEntities, knwlEntities, ner;

  Promise = require('bluebird');

  knwlEntities = require('./services/knwlPromise');

  alchemyEntities = require('./services/alchemyPromise');

  ner = (function(_this) {
    return function(text, apiKeys) {
      var collectEntities;
      collectEntities = function(entityList) {
        var entities, entity, i, len, pluralTypeName;
        entities = {};
        for (i = 0, len = entityList.length; i < len; i++) {
          entity = entityList[i];
          pluralTypeName = entity.type + 'List';
          if (entities[pluralTypeName] == null) {
            entities[pluralTypeName] = [entity];
          } else {
            entities[pluralTypeName].push(entity);
          }
        }
        return entities;
      };
      if (text == null) {
        throw new Error("input is " + text);
      }
      return Promise.join(knwlEntities(text), alchemyEntities(text, apiKeys.alchemy), function(knwlRes, alchemyRes) {
        return new Promise(function(resolve) {
          var entities;
          entities = collectEntities(knwlRes.concat(alchemyRes));
          return resolve(entities);
        });
      });
    };
  })(this);

  module.exports = ner;

}).call(this);
